// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.3
// source: product.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "product";

export interface ProductData {
  id: string;
  name: string;
  sku: string;
  stock: number;
  price: number;
}

/** CreateProduct */
export interface CreateProductRequest {
  name: string;
  sku: string;
  stock: number;
  price: number;
}

export interface CreateProductResponse {
  status: number;
  error: string[];
  id: string;
}

/** FindOne */
export interface FindOneRequest {
  id: string;
}

export interface FindOneResponse {
  status: string;
  error: string[];
  data: ProductData | undefined;
}

/** FindAll */
export interface FindAllRequest {
  page: number;
  limit: number;
}

export interface FindAllResponse {
  status: number;
  error: string[];
  data: ProductData[];
  total: number;
}

/** FindByShop */
export interface FindByShopRequest {
  shopId: string;
  page: number;
  limit: number;
}

export interface FindByShopResponse {
  status: number;
  error: string[];
  data: ProductData[];
  total: number;
}

/** UpdateProduct */
export interface UpdateProductRequest {
  id: string;
  name: string;
  sku: string;
  stock: number;
  price: number;
}

export interface UpdateProductResponse {
  status: number;
  error: string[];
}

/** DeleteProduct */
export interface DeleteProductRequest {
  id: string;
}

export interface DeleteProductResponse {
  status: number;
  error: string[];
}

export interface DecreaseStockRequest {
  id: string;
}

export interface DecreaseStockResponse {
  status: number;
  error: string[];
}

export const PRODUCT_PACKAGE_NAME = "product";

export interface ProductServiceClient {
  createProduct(request: CreateProductRequest): Observable<CreateProductResponse>;

  findOne(request: FindOneRequest): Observable<FindOneResponse>;

  decreaseStock(request: DecreaseStockRequest): Observable<DecreaseStockResponse>;
}

export interface ProductServiceController {
  createProduct(
    request: CreateProductRequest,
  ): Promise<CreateProductResponse> | Observable<CreateProductResponse> | CreateProductResponse;

  findOne(request: FindOneRequest): Promise<FindOneResponse> | Observable<FindOneResponse> | FindOneResponse;

  decreaseStock(
    request: DecreaseStockRequest,
  ): Promise<DecreaseStockResponse> | Observable<DecreaseStockResponse> | DecreaseStockResponse;
}

export function ProductServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createProduct", "findOne", "decreaseStock"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProductService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProductService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PRODUCT_SERVICE_NAME = "ProductService";
